Plugin:
  Command_Aliases: gp,gamepoints,points,coins
  Language: en
  Prefix: 'GamePoints'

Database:
  Type: SQLite
  Auto_Save_Interval: 15
  Instant_Save: true
  MySQL:
    Username: 'root'
    Password: 'root'
    Host: 'localhost:3306'
    Database: 'minecraft'
  Purge:
    Enabled: false
    For_Inactive_Days: 60

General:
  Points_Name: 'Game Points'
  Start_Balance: 0
  Balance_Top:
    Update_Interval: 20

Store:
  Product:
    Display:
      Format:
        - '%product_description%'
        - '&7'
        - '&7Default Price: &f%product_price_final% %points_name%'
        - '&7Your Price: &f%product_price_inherited% %points_name%'
        - '&7'
        - '&6Your Balance: &e%user_balance% %points_name%'
        - '&bOne-Time Purchase: &f%product_one_time_purchase%'
        - '&7'
        - '%purchase%'
    Purchase:
      Format:
        Already_Have:
          - '&cYou already have purchased this product!'
        Cooldown:
          - '&6You can purchase again in: &e%product_cooldown%'
        Available:
          - '&aClick to purchase!'

Transaction_Logs:
  Format: '%user_name% purchased ''%product_id%'' in ''%store_id%'' store for %product_price_inherited% points.'
  Date: 'dd/MM/yyyy HH:mm:ss'
  Console: true
  File: true