Plugin:
  Command_Aliases: gp,gamepoints,points,coins
  Language: en
  Prefix: '&e%plugin_name% &8» &7'
  Name: 'GamePoints'

Database:
  Auto_Save_Interval: 20
  Sync_Interval: 60
  Type: SQLITE
  Table_Prefix: 'gamepoints'
  MySQL:
    Username: root
    Password: root
    Host: localhost
    Database: minecraft
  SQLite:
    FileName: data.db
  Purge:
    Enabled: false
    For_Period: 60

General:
  # Convert user data from other points plugins.
  Conversion:
    # Enable/Disable the converter on server startup.
    # This setting will be auto disabled once the conversion is done.
    Enabled: false
    # A plugin to convert data from.
    # Available options: PlayerPoints.
    From: 'none'
  Points_Name: 'Game Points'
  Start_Balance: 0
  Balance_Top:
    Update_Interval: 20

Store:
  Product:
    Display:
      Format:
        - '%product_description%'
        - '&7'
        - '&7Default Price: &f%product_price_final% %points_name%'
        - '&7Your Price: &f%product_price_inherited% %points_name%'
        - '&7'
        - '&6Your Balance: &e%user_balance% %points_name%'
        - '&bOne-Time Purchase: &f%product_one_time_purchase%'
        - '&7'
        - '%purchase%'
    Purchase:
      Format:
        Already_Have:
          - '&cYou already have purchased this product!'
        Cooldown:
          - '&6You can purchase again in: &e%product_cooldown%'
        Available:
          - '&aClick to purchase!'

Transaction_Logs:
  Format: '%user_name% purchased ''%product_id%'' in ''%store_id%'' store for %product_price_inherited% points.'
  Date: 'dd/MM/yyyy HH:mm:ss'
  Console: true
  File: true