main: su.nightexpress.gamepoints.GamePoints
version: '1.3.1'
name: GamePoints
author: NightExpress
desciption: Additional virtual currency with internal GUI shop.
depend: [ NexEngine ]
softdepend: [ PlaceholderAPI ]
api-version: 1.17
permissions:
#--------------------------------------------------------#
  gamepoints.admin:
    description: Access to all the plugin functions.
    default: op
    children:
      gamepoints.command: true
      gamepoints.store.*: true
#--------------------------------------------------------#
  gamepoints.command:
    description: Access to all plugin commands.
    default: op
    children:
      gamepoints.command.add: true
      gamepoints.command.addpurchase: true
      gamepoints.command.pay: true
      gamepoints.command.balance: true
      gamepoints.command.balance.others: true
      gamepoints.command.balancetop: true
      gamepoints.command.removepurchase: true
      gamepoints.command.set: true
      gamepoints.command.store: true
      gamepoints.command.take: true

  gamepoints.command.add:
    description: Allows to use '/gamepoints add' command.
    default: op

  gamepoints.command.addpurchase:
    description: Allows to use '/gamepoints addpurchase' command.
    default: op

  gamepoints.command.balance:
    description: Allows to use '/gamepoints balance' command.
    default: true
    children:
      gamepoints.command.balance.others: false

  gamepoints.command.balance.others:
    description: Allows to use '/gamepoints balance' command on other players.
    default: op

  gamepoints.command.balancetop:
    description: Allows to use '/gamepoints balancetop' command.
    default: true

  gamepoints.command.pay:
    description: Allows to use '/gamepoints pay' command.
    default: op

  gamepoints.command.removepurchase:
    description: Allows to use '/gamepoints removepurchase' command.
    default: op

  gamepoints.command.set:
    description: Allows to use '/gamepoints set' command.
    default: op

  gamepoints.command.store:
    description: Allows to use '/gamepoints store' command.
    default: true

  gamepoints.command.take:
    description: Allows to use '/gamepoints take' command.
    default: op
#--------------------------------------------------------#
  gamepoints.store.*:
    description: Grants access to all stores.
    default: op
#--------------------------------------------------------#