rank_vip:
  Name: '&d&nVIP Rank'
  Description:
  - '&7Example rank lore...'
  Price: 50
  Purchase_Cooldown: -1
  Priority: 10
  Inheritance:
    Rewards: []
    Price: []
  Preview:
    Material: STONE_PICKAXE
    Item_Flags:
      - '*'
  Rewards:
    Commands:
    - '[CONSOLE] broadcast &f%player% &7just purchased the &dVIP Rank&7!'
    - '[CONSOLE] lp user %player% group parent set vip'
  Store:
    Page: 1
    Slot: 11

rank_vip_plus:
  Name: '&aVIP+ Rank'
  Description:
  - '&7Example rank lore...'
  Price: 150
  Purchase_Cooldown: -1
  Priority: 20
  Inheritance:
    Rewards: []
    Price:
    - rank_vip
  Preview:
    Material: IRON_PICKAXE
    Item_Flags:
      - '*'
  Rewards:
    Commands:
    - '[CONSOLE] broadcast &f%player% &7just purchased the &aVIP+ Rank&7!'
    - '[CONSOLE] lp user %player% group parent set vip_plus'
  Store:
    Page: 1
    Slot: 13

rank_mvp:
  Name: '&bMVP Rank'
  Description:
  - '&7Example rank lore...'
  Price: 300
  Purchase_Cooldown: -1
  Priority: 30
  Inheritance:
    Rewards: []
    Price:
    - rank_vip
    - rank_vip_plus
  Preview:
    Material: DIAMOND_PICKAXE
    Item_Flags:
      - '*'
  Rewards:
    Commands:
    - '[CONSOLE] broadcast &f%player% &7just purchased the &bMVP Rank&7!'
    - '[CONSOLE] lp user %player% group parent set mvp'
  Store:
    Page: 1
    Slot: 15
